### ISSUE TITLE
Unterseiten werden nicht indiziert

### ISSUE THREAD

**Issue by simonreitinger** [Sioweb/glossar_c4#10]
Beim Aufbauen des Glossars werden geschachtelte Unterseiten nicht berücksichtigt. `$objPage` ist hier immer die Elternseite, wobei diese dann auch immer überschrieben wird.

**Comment by Sioweb** [comment]
Ho!

ich habe gestern Version 2 veröffentlicht. Besteht das Problem weiterhin, falls ja, meinst du mit geschachtelte Unterseiten einfach generell Unterseiten?

**Comment by simonreitinger** [comment]
Super, funktioniert soweit! Im Installtool ist noch ein Feld, das nicht erkannt wird. Hab hierfür aber ein neues Issue angelegt.
