### ISSUE TITLE
Keywords werden nicht gefunden

### ISSUE THREAD

**Issue by simonreitinger** [Sioweb/glossar_c4#11]
Beim Erstellen des Glossars (Systemwartung) habe ich das Problem, dass Keywords nicht gefunden werden, obwohl sie auf der Seite vorkommen.

Ich glaube es liegt an `strip_tags($strContent)`. Da hier das komplette Dokument geparst wird, bleibt bei mir meistens nur der Title übrig. Link dazu:

https://github.com/Sioweb/glossar_c4/blob/master/src/Resources/contao/classes/RebuildGlossar.php#L136-L141

**Comment by Sioweb** [comment]
Ho! & Danke

ich bin nicht 100% sicher, aber in der neuen Version sollte das Problem behoben sein.
