### ISSUE TITLE
singleSRC bleibt im Installtool hängen

### ISSUE THREAD

**Issue by simonreitinger** [Sioweb/glossar_c4#14]
![Bildschirmfoto 2019-04-15 um 09 40 49](https://user-images.githubusercontent.com/26705426/56115214-34939900-5f63-11e9-9bfa-60b4044c823d.png)

Wenn ich das Installtool aufrufe, bleibt das Feld `singleSRC` "hängen". Wenn man im Entity `Terms` die `options` rausnimmt, sollte es nach der Installation verschwinden.

**Comment by Sioweb** [comment]
Danke für deine Hilfe, 

das prüfe ich nacher, ich denke ich brauche die option nullable=true, oder evt. kann ich auch einen Standardwert "0" angeben.

**Comment by Sioweb** [comment]
Danke, hat funktioniert!

**Comment by simonreitinger** [comment]
@Sioweb leider funktioniert 2.0.3 auch nicht 😅 

Die korrekte Annotation lautet 
`@ORM\Column(type="binary", length=16, nullable=true)`. 

Das ergibt dann die korrekte Definition `varbinary(16) DEFAULT NULL` im Installtool.

`nullable` gehört nicht in das Options Attribut: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/annotations-reference.html#e0432135e59de6f3339bb815e6877ec43fb0aae8

Mit v2.0.3 hat man sonst das Problem, dass man wegen dem fehlenden Default keine neuen Einträge erstellen kann:
![Bildschirmfoto 2019-04-15 um 16 37 07](https://user-images.githubusercontent.com/26705426/56141251-beac2380-5f9c-11e9-8b49-90dd8c974cac.png)

**Comment by Sioweb** [comment]
Ah mist, ich habs getestet ohne den Cache zu leeren, das Nullable ist nun gescheit drin :) danke für deinen Aufwand!

**Comment by simonreitinger** [comment]
@Sioweb kein Problem! 😄
