### ISSUE TITLE
Warnung beim Install-Tool unter Contao 4.4

### ISSUE THREAD

**Issue by MacKP** [Sioweb/glossar_c4#4]
Ich erhalte beim Aufruf vom Install-Tool folgende Warnung:
`Warning: array_keys() expects parameter 1 to be array, null given in xxx_contao4/var/cache/prod/contao/dca/tl_settings.php on line 505`

Ist jetzt nur eine unschönheit.

Viele Grüße
BTW: Danke für die Bereitstellung in Composer! Das ist super. So kann ich viel schneller und einfacher mal ein Update machen zum testen etc. ;-)

**Comment by Sioweb** [comment]
Der Fehler müsste behoben sein.

**Comment by Sioweb** [comment]
Könntest du mir das kurz bestätigen?

Btw: gerne :)

**Comment by Sioweb** [comment]
Ah der halbe Glossar hat nicht mehr gescheit funktioniert, jetzt funktioniert es vermutlich besser.

Die Links im Frontend funktionieren auch wieder.

Zusätzlich sind jetzt auch nummerische Werte möglich 3M-WhatEver. Dazu hat die Pagination jetzt zusätzlich 0-9 Werte.

Lg
Sascha
