### ISSUE TITLE
Fehler beim anlegen von neuen Seiten unter Contao 4.4

### ISSUE THREAD

**Issue by MacKP** [Sioweb/glossar_c4#5]
Ich erhalte beim anlegen von neuen Seiten leider Warnungen (sorgen allerdings dafür, das ich da nicht direkt weiter komme, sondern immer wieder rumklicken muss wie wild):
`Warning: asort() expects parameter 1 to be array, boolean given in xxx_contao4/vendor/metamodels/core/src/BackendIntegration/SearchablePages.php on line 407

Warning: Invalid argument supplied for foreach() in xxx_contao4/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Automator.php on line 351

Warning: Cannot modify header information - headers already sent by (output started at xxx_contao4/vendor/metamodels/core/src/BackendIntegration/SearchablePages.php:407) in xxx_contao4/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 675
`

Eventuell hängt das mit #4  zusammen. Bin mir da aber nicht sicher.

Viele Grüße

**Comment by MacKP** [comment]
Oh man.. ich hab ganz überlesen, dass es hier ein Fehler von MetaModels 2.1 ist.. sorry..

**Comment by discordier** [comment]
Ist kein Fehler von MetaModels sondern von glossar.
Der Hook [getSearchablePages.html](https://docs.contao.org/books/api/extensions/hooks/getSearchablePages.html#getsearchablepages) Soll ein array von URLs returnen.
Diese Erweiterung hier returned jedoch [false](https://github.com/Sioweb/glossar_c4/blob/fea90428d61a105775adb51b67b062093ba3a25b/src/Resources/contao/classes/Glossar.php#L505) wie in commit fea90428d61a105775adb51b67b062093ba3a25b eingebaut.
Dies muss wie folgt geaendert werden:
```diff
-       return false;
+       return [];
```

**Comment by Sioweb** [comment]
Ho! Danke euch.

Ich hab den Return-Wert angepasst.
