### ISSUE TITLE
js und css wird im frontend nicht geladen

### ISSUE THREAD

**Issue by rorych** [Sioweb/glossar_c4#6]
Erstmals ein fettes Kompliment! Ein echt umfangreiches und extrem durchdachtes Plugin - **DANKE**.

Habe zurzeit noch etwas Probleme mit dem Javascript jenes per Seitenlayout eingebunden werden sollte. Das jQuery Script wird ausgeführt, aber das glossar.js File wurde nie geladen.

Im Quellcode habe ich gesehen, dass es im config.php per $GLOBALS['TL_CSS'][] aus dem Ordner "web/bundles/siowegglossar/..." geladen wird. Der Symlink im bundles Ordner fehlt jedoch.
Dadurch kann es nicht geladen werden.

Wie haben Contao Standard 4.4.16 im Einsatz und haben die Symlinks, Dev-Cache und Prod-Cache schon mehrfach neugeladen, dennoch wird der Symlink nicht angelegt und somit auch die .css und .js Files nicht geladen.

Woran könnte das liegen?

**Comment by rorych** [comment]
Habe noch etwas getestet und nach x Versuchen ist der Symlink nun vorhanden.
Dennoch wird das js und css noch nicht eingebunden.

Erst wenn ich im config.php das Verzeichnis der beiden Files anpassen. Konkret wenn ich das "web" vor dem Pfad "bundles/siowebglossar/..." entferne:

**Vorher**
```php
if(TL_MODE == 'FE') {
	$GLOBALS['TL_CSS'][] = 'web/bundles/siowebglossar/css/glossar.min.css|static';
	if(empty($GLOBALS['TL_CONFIG']['disableToolTips'])) {
		$GLOBALS['TL_JAVASCRIPT'][] = 'web/bundles/siowebglossar/js/glossar.js|static';
	}
}
```

**Nachher**
```php
if(TL_MODE == 'FE') {
	$GLOBALS['TL_CSS'][] = 'bundles/siowebglossar/css/glossar.min.css|static';
	if(empty($GLOBALS['TL_CONFIG']['disableToolTips'])) {
		$GLOBALS['TL_JAVASCRIPT'][] = 'bundles/siowebglossar/js/glossar.js|static';
	}
}
```

Muss das so sein?
Gem. Contao muss doch das DomainMapping  ins web zeigen, somit erübrigt sich das hinzufügen des Ordners in diesem Pfad, oder?

**Comment by Sioweb** [comment]
Super danke! Habe ich übernommen.
