### ISSUE TITLE
Abstand nach Glossar Element

### ISSUE THREAD

**Issue by rorych** [Sioweb/glossar_c4#7]
Habe festgestellt, dass nach dem eingesetzten span ein Abstand eingefügt wird, wenn anschliessend ein Zeichen besteht, kann das sein?

Beispiel mit dem Begriff "amet", vorher:
Lorem ipsum dolor sit **amet**, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat..

Nachher:
Lorem ipsum dolor sit **amet** , consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat...

Die ganze Logik wie die Begriffe ersetzt werden, konnte ich leider nicht komplett nachvollziehen, daher kann ich nicht genau sagen, woran das liegen könnte - oder handelt es sich hier um das gewünschte Verhalten?

**Comment by Sioweb** [comment]
Ho! Ein jahr später - sry dafür - das ist nun in Version 2 behoben :)
