### ISSUE TITLE
Contao Managed Edition setLoadAfter for Calendar

### ISSUE THREAD

**Issue by rorych** [Sioweb/glossar_c4#8]
Hi there 

We just changed a installation from standard to managed-edition and it seems this Bundle is not working correctly and i think i know why.

In our own Bundle we are also extending the ContaoCalendarBundle and that the ManagerPlugin can do that, we had to define the ContaoCalendarBundle as a "setLoadAfter" Requirement.

In your Plugin.php you seem to only specify the ContaoCoreBundle but i think you also need to define:

`
->setLoadAfter(
    [
        'Contao\CoreBundle\ContaoCoreBundle',
        'Contao\CalendarBundle\ContaoCalendarBundle'
    ]
)
`

**Comment by Sioweb** [comment]
Top danke dir. Habe ich so eingebaut.
